window.addEventListener("load", mytrad());
var trad = `
<div style="display:fixed;z-index:5000;top:5%;right:5%">
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
    <div>%%lang%%</div>
</div>`;
function mytrad() {
    document.append(trad);
}